packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@prisma/engines'
  - bcrypt
  - prisma
  - sharp
  - unrs-resolver
ignoredBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - prisma
  - sharp
  - unrs-resolver
allowBuilds:
  '@apollo/protobufjs': true
  '@nestjs/core': true
  '@prisma/engines': true
  bcrypt: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
